### ISSUE TITLE
Verus Anti-cheat (Error on join)

### ISSUE THREAD

**Issue by ignMixha** [Imanity-Software/iSpigot-Issues#3]
Describe the bug - On-join or Relog an error comes up with verus anti-cheat.

To Reproduce Steps to reproduce the behavior: join the server or relog

Desktop (please complete the following information):

OS: Ubuntu
Version: 16.04

Full dump file (/iSpigot dump)
iSpigot version=1.2.3
license server version=null
TPS=[19.999990176004825, 19.999988900006162, 19.99999951466668, 20.000000008222223]
Logic tick=478647.0
World tick=351398.0
Late bind=false
OS=Linux
Java=1.8.0_242-8u242-b08-0ubuntu3~16.04-b08

World=world
Chunks=256
Entities=75
Players=0

World=world_the_end
Chunks=0
Entities=0
Players=0

World=world_nether
Chunks=0
Entities=0
Players=0

license_ssl_connection=true
auto_update=true
knockback_aliases=[kb]
weather_changes=false
use_higher_durability=true
use_playerdata=true
infinite_water=true
native_19_support=false
replace1_7title_as_chat=true
legacy_17_support=true
use_player_move_event=true
block_operations=true
do_chunk_unload=true
enable_mob_ai=true
disable_1_8entity_spawn_naturally=true
disable_1_8_stone_generation=false
tnt_optimization=false
optimizeLiquidExplosions=false
hide_tnt_entities=false
hide_falling_block_entities=false
pearl_taliban=true
pearl_through_fence_gate=true
pearl_through_tripwire=true
spawn_endermite=true
old_enchanting=true
show_hidden_player_in_tablist=false
integer_health_criteria=false
ping_command_enabled=false
cpu_information_in_tps=true
block_reload_command=true
cannon_break_obsidian=false
explode_break_blocks=false
explode_fast_block_breaking=false
showExplosionEffects=false
explode_optimized_typeA=false
explode_optimized_typeB=false
explode_optimized_typeC=false
explode_optimized_typeD=false
cannon_left_shooting=false
async_hit_detection=true
async_potion_movement=true
hit_detection_thread_type=SCHEDULED_EXECUTOR
potion_movement_thread_type=SCHEDULED_EXECUTOR
multiple_thread_world=false
world_thread_count=2
keep_alive_packet_frequency=20
restartType=STOP
custom_plan_ping=null
custom_plan_ping_other=null
custom_plan_server_name=null
custom_plan_version=null
custom_plan_tps=null
custom_plan_tps_regular=null

Plugins:
  ViaVersion:
    Version: 2.2.3
    Author: [_MylesC, creeper123123321, Gerrygames, KennyTV, Matsv]
    Main: us.myles.ViaVersion.ViaVersionPlugin
    Enabled: true
  ViaRewind:
    Version: 1.4.4
    Author: [Gerrygames]
    Main: de.gerrygames.viarewind.BukkitPlugin
    Enabled: true
  CoreProtect:
    Version: 2.12.0
    Author: [Intelli]
    Main: net.coreprotect.CoreProtect
    Enabled: true
  iSpigotEquipmentSetAddon:
    Version: 1.0.0
    Author: []
    Main: spg.lgdev.addons.iSpigotEquipmentSet
    Enabled: true
  FastAsyncWorldEdit:
    Version: 19.11.13-5505943-1282-22.3.5
    Author: [Empire92]
    Main: com.boydti.fawe.bukkit.BukkitMain
    Enabled: true
  Verus:
    Version: 1.0
    Author: [verusdev.xyz]
    Main: me.levansj01.launcher.VerusLauncher
    Enabled: true
  PermissionsEx:
    Version: 1.23.4
    Author: [[t3hk0d3, zml]]
    Main: ru.tehkode.permissions.bukkit.PermissionsEx
    Enabled: true
  PlugMan:
    Version: 2.0.8
    Author: [rylinaux]
    Main: com.rylinaux.plugman.PlugMan
    Enabled: true
  Broadcaster:
    Version: 5
    Author: [MrFantasy_]
    Main: spigot.mrfantasy.broadcaster.Main
    Enabled: true
  Vault:
    Version: 1.5.6-b49
    Author: [cereal, Sleaker, mung3r]
    Main: net.milkbowl.vault.Vault
    Enabled: true
  ProtocolLib:
    Version: 4.5.0
    Author: [dmulloy2, comphenix]
    Main: com.comphenix.protocol.ProtocolLib
    Enabled: true
  PlatinumKits:
    Version: 1.4.10
    Author: []
    Main: me.darkknights22.platinumkits.PlatinumKits
    Enabled: true
  WorldEdit:
    Version: 6.1.7;dd00bb1
    Author: []
    Main: com.sk89q.worldedit.bukkit.WorldEditPlugin
    Enabled: true
  Lazarus:
    Version: 0.6.2
    Author: [qIooIp]
    Main: me.qiooip.lazarus.Lazarus
    Enabled: true
  HolographicDisplays:
    Version: 2.4.1
    Author: []
    Main: com.gmail.filoghost.holographicdisplays.HolographicDisplays
    Enabled: true
  ServerListPlus:
    Version: 3.4.8
    Author: [Minecrell <https://github.com/Minecrell>]
    Main: net.minecrell.serverlistplus.bukkit.BukkitPlugin
    Enabled: true
  CrateReloaded:
    Version: 2.0.18
    Author: [dinosaur]
    Main: com.hazebyte.crate.cratereloaded.CorePlugin
    Enabled: true
  LiteBans:
    Version: 2.4.7
    Author: [Ruan]
    Main: litebans.E
    Enabled: true

**Comment by LeeGodSRC** [comment]
Please put the error log into the issue commit

**Comment by ignMixha** [comment]
[00:22:08 ERROR]: [Verus] Failed to handle incoming packet
io.netty.util.IllegalReferenceCountException: refCnt: 0
        at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1187) ~[spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.buffer.UnpooledHeapByteBuf.capacity(UnpooledHeapByteBuf.java:101) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketDataSerializer.capacity(SourceFile:239) ~[spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.buffer.UnpooledHeapByteBuf.setBytes(UnpooledHeapByteBuf.java:221) ~[spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:850) ~[spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.buffer.Unpooled.copiedBuffer(Unpooled.java:416) ~[spigot.jar:git-iSpigot-PaperEdition]
        at me.levansj01.verus.compat.v1_8_R3.packets.SPacketPlayInCustomPayload.accept(Unknown Source) ~[?:?]
        at me.levansj01.verus.compat.v1_8_R3.packets.SPacketPlayInCustomPayload.accept(Unknown Source) ~[?:?]
        at me.levansj01.verus.compat.v1_8_R3.PacketManager.transform(Unknown Source) ~[?:?]
        at me.levansj01.verus.compat.v1_8_R3.PacketHandler.handle(Unknown Source) ~[?:?]
        at me.levansj01.verus.compat.v1_8_R3.PacketHandler.channelRead(Unknown Source) [?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-iSpigot-PaperEdition]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) [ProtocolLib.jar:4.5.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot.jar:git-iSpigot-PaperEdition]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by bublif** [comment]
Same problem over here. Still waiting for fix.

**Comment by LeeGodSRC** [comment]
Fixed
